// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmergencyResponseDemo) DeepCopyInto(out *EmergencyResponseDemo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmergencyResponseDemo.
func (in *EmergencyResponseDemo) DeepCopy() *EmergencyResponseDemo {
	if in == nil {
		return nil
	}
	out := new(EmergencyResponseDemo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EmergencyResponseDemo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmergencyResponseDemoList) DeepCopyInto(out *EmergencyResponseDemoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EmergencyResponseDemo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmergencyResponseDemoList.
func (in *EmergencyResponseDemoList) DeepCopy() *EmergencyResponseDemoList {
	if in == nil {
		return nil
	}
	out := new(EmergencyResponseDemoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EmergencyResponseDemoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmergencyResponseDemoSpec) DeepCopyInto(out *EmergencyResponseDemoSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmergencyResponseDemoSpec.
func (in *EmergencyResponseDemoSpec) DeepCopy() *EmergencyResponseDemoSpec {
	if in == nil {
		return nil
	}
	out := new(EmergencyResponseDemoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmergencyResponseDemoStatus) DeepCopyInto(out *EmergencyResponseDemoStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmergencyResponseDemoStatus.
func (in *EmergencyResponseDemoStatus) DeepCopy() *EmergencyResponseDemoStatus {
	if in == nil {
		return nil
	}
	out := new(EmergencyResponseDemoStatus)
	in.DeepCopyInto(out)
	return out
}
